Repository apache/logging-log4j2, pull requests merged in 2023-01, with the labels that each got.

#1141 (doc) Use Gradle platform to import Log4j BOM in Gradle 5.0+
  src/site/markdown/maven-artifacts.md.vm
Labels: documentation

#1069 Update exception message to refer to log4j-slf4j2-impl
  log4j-slf4j2-impl/src/main/java/org/apache/logging/slf4j/Log4jLoggerFactory.java
Labels: bug

#1172 Switch from JIRA to GitHub issues
  CONTRIBUTING.md
  README.md
  pom.xml
  src/changelog/.2.x.x/1172_switch_from_jira_to_github_issues.xml
  src/site/asciidoc/support.adoc
  src/site/markdown/support.md
  src/site/site.xml
  src/site/xdoc/guidelines.xml
Labels: build

#1197 Serialize cached location
  log4j-core-test/src/test/java/org/apache/logging/log4j/core/impl/MutableLogEventTest.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/impl/Log4jLogEvent.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/impl/MutableLogEvent.java
  src/changelog/.2.x.x/1197_preserve_location.xml
Labels: bug, api
