Repository apache/logging-log4j2, pull requests merged in 2023-10, with the labels that each got.

#1537 (doc) fix the disableAnsi default value description
  src/site/xdoc/manual/layouts.xml.vm
Labels: bug, documentation

#1549 Issue 1445 - Fix RollingFileManager and FileRenameAction
  log4j-core-test/src/test/java/org/apache/logging/log4j/core/appender/rolling/RollingFileManagerTest.java
  log4j-core-test/src/test/java/org/apache/logging/log4j/core/appender/rolling/action/FileRenameActionTest.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/appender/rolling/RollingFileManager.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/appender/rolling/action/FileRenameAction.java
  src/changelog/.2.x.x/1445_fix_synchronous_rolling_file_manager.xml
Labels: bug

#1637 Add a warning in case of incorrect syntax of highlighting style.
  log4j-core-test/src/test/java/org/apache/logging/log4j/core/pattern/HighlightConverterTest.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/pattern/AnsiEscape.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/pattern/HighlightConverter.java
  src/changelog/.2.x.x/1545_add_warn_in_case_of_incorrect_syntax_of_highlighting_style.xml
Labels: enhancement

#1833 Improve warning message if multi-release JARs are not supported
  log4j-api/src/main/java/org/apache/logging/log4j/util/StackLocator.java
Labels: enhancement

#1834 Add `columnType` as alias for column mapping `type` attribute
  log4j-core-test/src/test/java/org/apache/logging/log4j/core/appender/db/jdbc/JdbcAppenderColumnMappingPropertiesTest.java
  log4j-core-test/src/test/resources/org/apache/logging/log4j/core/appender/db/jdbc/JdbcAppenderColumnMappingPropertiesTest.properties
  log4j-core/src/main/java/org/apache/logging/log4j/core/appender/db/ColumnMapping.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/appender/db/jdbc/JdbcDatabaseManager.java
  src/changelog/.2.x.x/1405_column_mapping_rename_type_attribute.xml
Labels: bug

#1683 Open `FileExtension` accessors (#1365)
  log4j-core/src/main/java/org/apache/logging/log4j/core/appender/rolling/FileExtension.java
Labels: enhancement, api

#1753 Issue 1275 broken javadoc
  log4j-api/src/main/java/org/apache/logging/log4j/BridgeAware.java
  log4j-api/src/main/java/org/apache/logging/log4j/Level.java
  log4j-api/src/main/java/org/apache/logging/log4j/message/AbstractMessageFactory.java
  log4j-api/src/main/java/org/apache/logging/log4j/message/FormattedMessageFactory.java
  log4j-api/src/main/java/org/apache/logging/log4j/message/LocalizedMessageFactory.java
  log4j-api/src/main/java/org/apache/logging/log4j/message/MessageFormatMessageFactory.java
  log4j-api/src/main/java/org/apache/logging/log4j/message/ParameterConsumer.java
  log4j-api/src/main/java/org/apache/logging/log4j/message/ParameterizedMessageFactory.java
  log4j-api/src/main/java/org/apache/logging/log4j/message/ParameterizedNoReferenceMessageFactory.java
  log4j-api/src/main/java/org/apache/logging/log4j/message/SimpleMessageFactory.java
  log4j-api/src/main/java/org/apache/logging/log4j/message/StringFormattedMessage.java
  log4j-api/src/main/java/org/apache/logging/log4j/message/StringFormatterMessageFactory.java
  log4j-api/src/main/java/org/apache/logging/log4j/message/StructuredDataId.java
  log4j-api/src/main/java/org/apache/logging/log4j/spi/MutableThreadContextStack.java
  log4j-api/src/main/java/org/apache/logging/log4j/util/EnglishEnums.java
  log4j-api/src/main/java/org/apache/logging/log4j/util/ProcessIdUtil.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/appender/AbstractOutputStreamAppender.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/appender/AbstractWriterAppender.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/appender/db/jdbc/JdbcDatabaseManager.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/appender/rolling/action/DeleteAction.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/appender/rolling/action/ScriptCondition.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/appender/rolling/action/SortingVisitor.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/appender/routing/PurgePolicy.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/async/DiscardingAsyncQueueFullPolicy.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/config/DefaultAdvertiser.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/config/Property.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/config/plugins/convert/Base64Converter.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/config/plugins/convert/HexConverter.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/filter/RegexFilter.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/filter/StringMatchFilter.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/impl/ExtendedClassInfo.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/impl/ExtendedStackTraceElement.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/impl/ThrowableFormatOptions.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/impl/ThrowableProxy.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/layout/AbstractLayout.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/layout/LevelPatternSelector.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/layout/MarkerPatternSelector.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/layout/PatternLayout.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/layout/ScriptPatternSelector.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/net/DatagramSocketManager.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/net/Facility.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/net/MulticastDnsAdvertiser.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/net/SslSocketManager.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/pattern/NamePatternConverter.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/pattern/RootThrowablePatternConverter.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/pattern/ThrowablePatternConverter.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/util/Constants.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/util/CronExpression.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/util/FileUtils.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/util/Loader.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/util/ReflectionUtil.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/util/datetime/FastDateParser.java
  pom.xml
Labels: enhancement
