Repository apache/logging-log4j2, pull requests merged in 2023-02, with the labels that each got.

#1193 remove liquibase-log4j2 module
  log4j-bom/pom.xml
  log4j-distribution/pom.xml
  log4j-liquibase/pom.xml
  log4j-liquibase/src/main/java/liquibase/ext/logging/log4j2/Log4j2Logger.java
  log4j-liquibase/src/test/java/liquibase/ext/logging/log4j2/LoggingTest.java
  log4j-liquibase/src/test/resources/log4j2-test.xml
  pom.xml
  src/changelog/.2.x.x/1193_remove_liquibase_log4j2_module.xml
  src/site/markdown/javadoc.md
  src/site/markdown/log4j-liquibase.md
  src/site/site.xml
Labels: plugins

#1263 [LOG4J2-3624] Protects `ServiceLoaderUtil` from unchecked exceptions
  log4j-api-test/src/test/java/org/apache/logging/log4j/test/BetterService.java
  log4j-api-test/src/test/java/org/apache/logging/log4j/test/Service.java
  log4j-api-test/src/test/java/org/apache/logging/log4j/test/Service1.java
  log4j-api-test/src/test/java/org/apache/logging/log4j/test/Service2.java
  log4j-api-test/src/test/java/org/apache/logging/log4j/util/ServiceLoaderUtilTest.java
  log4j-api-test/src/test/resources/META-INF/services/org.apache.logging.log4j.test.BetterService
  log4j-api-test/src/test/resources/META-INF/services/org.apache.logging.log4j.test.Service
  log4j-api-test/src/test/resources/org/apache/logging/log4j/test/ForceLinkageError.class
  log4j-api/src/main/java/org/apache/logging/log4j/util/ServiceLoaderUtil.java
  src/changelog/.2.x.x/LOG4J2-3624_Catch_unchecked_exception_from_ServiceLoader.xml
Labels: bug

#1165 [LOG4J2-3642] Consider Osgi versions older than 1.5 as not available.
  log4j-api-test/pom.xml
  log4j-api-test/src/test/java/org/apache/logging/log4j/util/ServiceLoaderUtilTest.java
  log4j-api/src/main/java/org/apache/logging/log4j/util/OsgiServiceLocator.java
  log4j-osgi/src/test/java/org/apache/logging/log4j/osgi/tests/AbstractLoadBundleTest.java
  src/changelog/.2.x.x/LOG4J2-3642_disable_OSGI_locator_if_not_OSGI.xml
Labels: bug

#1271 Bump Fluido skin from 1.8 to 1.11.2
  src/site/site.xml
Labels: documentation

#1270 Rename POM Log4j* properties
  log4j-distribution/pom.xml
  pom.xml
Labels: documentation
