Repository apache/logging-log4j2, pull requests merged in 2024-10, with the labels that each got.

#3030 Address Type Resolution Issues in Legacy Migration Using log4j-1.2-api with OpenJDK Compilation
  log4j-1.2-api/src/main/java/org/apache/log4j/Logger.java
  src/changelog/.2.x.x/3030_fix_log4j1_getLogger.xml
Labels: bug, api, legacy-1.2-bridge

#2691 Consolidate stack trace rendering in Pattern Layout
  log4j-api-test/pom.xml
  log4j-core-test/pom.xml
  log4j-core-test/src/test/java/foo/TestFriendlyException.java
  log4j-core-test/src/test/java/org/apache/logging/log4j/core/EventParameterMemoryLeakTest.java
  log4j-core-test/src/test/java/org/apache/logging/log4j/core/appender/rolling/RollingAppenderOnStartupTest.java
  log4j-core-test/src/test/java/org/apache/logging/log4j/core/impl/NestedLoggingFromThrowableMessageTest.java
  log4j-core-test/src/test/java/org/apache/logging/log4j/core/impl/ThrowableProxyHelperTest.java
  log4j-core-test/src/test/java/org/apache/logging/log4j/core/impl/ThrowableProxyTest.java
  log4j-core-test/src/test/java/org/apache/logging/log4j/core/pattern/ExtendedThrowablePatternConverterTest.java
  log4j-core-test/src/test/java/org/apache/logging/log4j/core/pattern/ExtendedThrowableTest.java
  log4j-core-test/src/test/java/org/apache/logging/log4j/core/pattern/RootThrowablePatternConverterTest.java
  log4j-core-test/src/test/java/org/apache/logging/log4j/core/pattern/RootThrowableTest.java
  log4j-core-test/src/test/java/org/apache/logging/log4j/core/pattern/ThrowablePatternConverterTest.java
  log4j-core-test/src/test/java/org/apache/logging/log4j/core/pattern/ThrowableTest.java
  log4j-core-test/src/test/resources/log4j-rootthrowablefilter.xml
  log4j-core-test/src/test/resources/log4j-throwable.xml
  log4j-core-test/src/test/resources/log4j-throwablefilter.xml
  log4j-core/src/main/java/org/apache/logging/log4j/core/impl/ExtendedClassInfo.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/impl/ExtendedStackTraceElement.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/impl/ThrowableFormatOptions.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/impl/ThrowableProxy.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/impl/ThrowableProxyHelper.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/impl/ThrowableProxyRenderer.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/impl/package-info.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/jackson/ExtendedStackTraceElementMixIn.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/jackson/ThrowableProxyMixIn.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/jackson/ThrowableProxyWithStacktraceAsStringMixIn.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/jackson/ThrowableProxyWithoutStacktraceMixIn.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/layout/PatternLayout.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/pattern/ClassResourceInfo.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/pattern/ExtendedThrowablePatternConverter.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/pattern/PatternParser.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/pattern/RootThrowablePatternConverter.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/pattern/ThrowableExtendedStackTraceRenderer.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/pattern/ThrowableInvertedStackTraceRenderer.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/pattern/ThrowablePatternConverter.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/pattern/ThrowablePropertyRenderer.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/pattern/ThrowableRenderer.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/pattern/ThrowableStackTraceRenderer.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/pattern/package-info.java
  log4j-perf-test/src/main/java/org/apache/logging/log4j/ThrowVsReturnBenchmark.java
  log4j-taglib/src/test/java/org/apache/logging/log4j/taglib/CatchingTagTest.java
  log4j-taglib/src/test/java/org/apache/logging/log4j/taglib/LoggingMessageTagSupportTest.java
  src/changelog/.2.x.x/2691_change_PatternLayout_exception_rendering.xml
  src/changelog/.2.x.x/2691_deprecate_ThrowableProxy.xml
  src/changelog/.2.x.x/2691_fix_PatternLayout_exception_rendering.xml
  src/site/antora/modules/ROOT/pages/manual/pattern-layout.adoc
Labels: layouts

#3047 Consolidate stack trace rendering in Pattern Layout
  log4j-async-logger/src/main/java/org/apache/logging/log4j/async/logger/RingBufferLogEvent.java
  log4j-async-logger/src/test/java/org/apache/logging/log4j/async/logger/RingBufferLogEventTest.java
  log4j-core-test/pom.xml
  log4j-core-test/src/main/java/org/apache/logging/log4j/core/test/layout/LogEventFixtures.java
  log4j-core-test/src/test/java/foo/TestFriendlyException.java
  log4j-core-test/src/test/java/org/apache/logging/log4j/core/EventParameterMemoryLeakTest.java
  log4j-core-test/src/test/java/org/apache/logging/log4j/core/appender/rewrite/MapRewritePolicyTest.java
  log4j-core-test/src/test/java/org/apache/logging/log4j/core/appender/rolling/RollingAppenderOnStartupTest.java
  log4j-core-test/src/test/java/org/apache/logging/log4j/core/impl/MutableLogEventTest.java
  log4j-core-test/src/test/java/org/apache/logging/log4j/core/impl/NestedLoggingFromThrowableMessageTest.java
  log4j-core-test/src/test/java/org/apache/logging/log4j/core/impl/ThrowableProxyHelperTest.java
  log4j-core-test/src/test/java/org/apache/logging/log4j/core/impl/ThrowableProxyTest.java
  log4j-core-test/src/test/java/org/apache/logging/log4j/core/pattern/ExtendedThrowablePatternConverterTest.java
  log4j-core-test/src/test/java/org/apache/logging/log4j/core/pattern/ExtendedThrowableTest.java
  log4j-core-test/src/test/java/org/apache/logging/log4j/core/pattern/RootThrowablePatternConverterTest.java
  log4j-core-test/src/test/java/org/apache/logging/log4j/core/pattern/RootThrowableTest.java
  log4j-core-test/src/test/java/org/apache/logging/log4j/core/pattern/ThrowablePatternConverterTest.java
  log4j-core-test/src/test/java/org/apache/logging/log4j/core/pattern/ThrowableTest.java
  log4j-core-test/src/test/resources/log4j-rootthrowablefilter.xml
  log4j-core-test/src/test/resources/log4j-throwable.xml
  log4j-core-test/src/test/resources/log4j-throwablefilter.xml
  log4j-core-test/src/test/resources/serializedEvent.dat
  log4j-core/src/main/java/org/apache/logging/log4j/core/AbstractLogEvent.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/LogEvent.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/impl/ExtendedClassInfo.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/impl/ExtendedStackTraceElement.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/impl/Log4jLogEvent.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/impl/MementoLogEvent.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/impl/MutableLogEvent.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/impl/ThrowableFormatOptions.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/impl/ThrowableProxy.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/impl/ThrowableProxyHelper.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/impl/ThrowableProxyRenderer.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/lookup/EventLookup.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/pattern/ClassResourceInfo.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/pattern/ExtendedThrowablePatternConverter.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/pattern/PatternParser.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/pattern/RootThrowablePatternConverter.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/pattern/ThrowableExtendedStackTraceRenderer.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/pattern/ThrowableInvertedStackTraceRenderer.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/pattern/ThrowablePatternConverter.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/pattern/ThrowablePropertyRenderer.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/pattern/ThrowableRenderer.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/pattern/ThrowableStackTraceRenderer.java
  log4j-csv/src/main/java/org/apache/logging/log4j/csv/layout/CsvLogEventLayout.java
  log4j-perf-test/src/main/java/org/apache/logging/log4j/ThrowVsReturnBenchmark.java
  src/changelog/.3.x.x/remove_ThrowableProxy.xml
  src/site/antora/modules/ROOT/pages/manual/pattern-layout.adoc
Labels: layouts

#3040 refactor: Migrate log4j-to-slf4j to JUnit5
  log4j-to-slf4j/pom.xml
  log4j-to-slf4j/src/test/java/org/apache/logging/slf4j/CallerInformationTest.java
  log4j-to-slf4j/src/test/java/org/apache/logging/slf4j/LoggerTest.java
Labels: tests

#3052 Migrate `log4j-jakarta-smtp` to JUnit 5
  log4j-jakarta-smtp/pom.xml
  log4j-jakarta-smtp/src/test/java/org/apache/logging/log4j/smtp/SmtpAppenderAsyncTest.java
  log4j-jakarta-smtp/src/test/java/org/apache/logging/log4j/smtp/SmtpAppenderTest.java
  log4j-jakarta-smtp/src/test/java/org/apache/logging/log4j/smtp/SmtpManagerTest.java
Labels: tests

#3053 Add `reachability-metadata.json` to all Log4j modules
  log4j-api/src/main/resources/META-INF/native-image/org.apache.logging.log4j/log4j-api/resource-config.json
  log4j-core-test/pom.xml
  log4j-core-test/src/test/java/org/apache/logging/log4j/core/config/plugins/processor/FakeAnnotations.java
  log4j-core-test/src/test/java/org/apache/logging/log4j/core/config/plugins/processor/FakePlugin.java
  log4j-core-test/src/test/java/org/apache/logging/log4j/core/config/plugins/processor/GraalVmProcessorTest.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/config/plugins/processor/GraalVmProcessor.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/config/plugins/processor/PluginProcessor.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/config/plugins/processor/internal/Annotations.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/config/plugins/processor/internal/ReachabilityMetadata.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/config/plugins/processor/package-info.java
  log4j-core/src/main/resources/META-INF/native-image/org.apache.logging.log4j/log4j-core/resource-config.json
  log4j-parent/pom.xml
Labels: graalvm

#3039 Remove ancient test fixtures and dependencies
  log4j-1.2-api/pom.xml
  log4j-1.2-api/src/main/java/org/apache/log4j/xml/XmlConfiguration.java
  log4j-1.2-api/src/test/java/org/apache/log4j/VelocityTest.java
  log4j-1.2-api/src/test/java/org/apache/log4j/util/AbsoluteDateAndTimeFilter.java
  log4j-1.2-api/src/test/java/org/apache/log4j/util/AbsoluteTimeFilter.java
  log4j-1.2-api/src/test/java/org/apache/log4j/util/Compare.java
  log4j-1.2-api/src/test/java/org/apache/log4j/util/ControlFilter.java
  log4j-1.2-api/src/test/java/org/apache/log4j/util/EnhancedJunitTestRunnerFilter.java
  log4j-1.2-api/src/test/java/org/apache/log4j/util/EnhancedLineNumberFilter.java
  log4j-1.2-api/src/test/java/org/apache/log4j/util/Filter.java
  log4j-1.2-api/src/test/java/org/apache/log4j/util/ISO8601Filter.java
  log4j-1.2-api/src/test/java/org/apache/log4j/util/JunitTestRunnerFilter.java
  log4j-1.2-api/src/test/java/org/apache/log4j/util/LineNumberFilter.java
  log4j-1.2-api/src/test/java/org/apache/log4j/util/RelativeTimeFilter.java
  log4j-1.2-api/src/test/java/org/apache/log4j/util/SunReflectFilter.java
  log4j-1.2-api/src/test/java/org/apache/log4j/util/Transformer.java
  log4j-1.2-api/src/test/java/org/apache/log4j/util/UnexpectedFormatException.java
  log4j-1.2-api/src/test/java/org/apache/log4j/util/XMLLineAttributeFilter.java
  log4j-1.2-api/src/test/java/org/apache/log4j/util/XMLTimestampFilter.java
  log4j-1.2-api/src/test/java/org/apache/log4j/xml/DOMTestCase.java
  log4j-1.2-api/src/test/resources/DOMTestCase/DOMTest4.xml
  log4j-1.2-api/src/test/resources/DOMTestCase/DOMTest4_A1.xml
  log4j-1.2-api/src/test/resources/DOMTestCase/categoryfactory1.xml
  log4j-1.2-api/src/test/resources/DOMTestCase/categoryfactory2.xml
  log4j-1.2-api/src/test/resources/DOMTestCase/loggerfactory1.xml
  log4j-1.2-api/src/test/resources/DOMTestCase/testThrowableRenderer.xml
  log4j-1.2-api/src/test/resources/DOMTestCase/throwableRenderer1.xml
  log4j-1.2-api/src/test/resources/hello.vm
  log4j-api-test/src/main/java/org/apache/logging/log4j/test/junit/TempLoggingDirectory.java
  log4j-api-test/src/test/java/org/apache/logging/log4j/test/junit/TempLoggingDirectoryTest.java
Labels: tests, legacy-1.2-bridge

#3054 Document GraalVM usage with Log4j
  src/site/antora/modules/ROOT/nav.adoc
  src/site/antora/modules/ROOT/pages/graalvm.adoc
  src/site/antora/modules/ROOT/pages/manual/installation.adoc
  src/site/antora/modules/ROOT/pages/manual/plugins.adoc
  src/site/antora/modules/ROOT/pages/release-notes.adoc
Labels: documentation, graalvm

#3069 Upgrades JUnit to version `5.11.2`
  log4j-api-test/src/main/java/org/apache/logging/log4j/test/junit/SetTestProperty.java
  log4j-api-test/src/main/java/org/apache/logging/log4j/test/junit/TempLoggingDir.java
  log4j-api-test/src/main/java/org/apache/logging/log4j/test/junit/UsingStatusListener.java
  log4j-api-test/src/main/java/org/apache/logging/log4j/test/junit/UsingTestProperties.java
  log4j-api-test/src/main/java/org/apache/logging/log4j/test/junit/package-info.java
  log4j-core-test/src/main/java/org/apache/logging/log4j/core/test/junit/LoggerContextSource.java
  log4j-core-test/src/main/java/org/apache/logging/log4j/core/test/junit/package-info.java
  log4j-parent/pom.xml
Labels: tests

#3073 Prefix stack traces with a newline in Pattern Layout
  log4j-async-logger/src/test/java/org/apache/logging/log4j/async/logger/AsyncLoggerTestArgumentFreedOnErrorTest.java
  log4j-async-logger/src/test/java/org/apache/logging/log4j/async/logger/QueueFullAsyncLogger3Test.java
  log4j-core-test/src/main/java/org/apache/logging/log4j/core/GarbageCollectionHelper.java
  log4j-core-test/src/main/java/org/apache/logging/log4j/core/test/internal/GcHelper.java
  log4j-core-test/src/main/java/org/apache/logging/log4j/core/test/internal/GcPressureGenerator.java
  log4j-core-test/src/test/java/foo/TestFriendlyException.java
  log4j-core-test/src/test/java/org/apache/logging/log4j/core/EventParameterMemoryLeakTest.java
  log4j-core-test/src/test/java/org/apache/logging/log4j/core/ReusableParameterizedMessageMemoryLeakTest.java
  log4j-core-test/src/test/java/org/apache/logging/log4j/core/appender/rolling/RollingAppenderDirectWriteTest.java
  log4j-core-test/src/test/java/org/apache/logging/log4j/core/impl/NestedLoggingFromThrowableMessageTest.java
  log4j-core-test/src/test/java/org/apache/logging/log4j/core/internal/GcHelperTest.java
  log4j-core-test/src/test/java/org/apache/logging/log4j/core/layout/PatternLayoutDefaultExceptionHandlerTest.java
  log4j-core-test/src/test/java/org/apache/logging/log4j/core/pattern/ExtendedThrowablePatternConverterTest.java
  log4j-core-test/src/test/java/org/apache/logging/log4j/core/pattern/RootThrowablePatternConverterTest.java
  log4j-core-test/src/test/java/org/apache/logging/log4j/core/pattern/ThrowablePatternConverterTest.java
  log4j-core-test/src/test/java/org/apache/logging/log4j/core/pattern/ThrowableTest.java
  log4j-core-test/src/test/java/org/apache/logging/log4j/core/util/ThrowablesTest.java
  log4j-core-test/src/test/resources/EventParameterMemoryLeakTest.xml
  log4j-core/src/main/java/org/apache/logging/log4j/core/pattern/ExtendedThrowablePatternConverter.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/pattern/RootThrowablePatternConverter.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/pattern/ThrowableExtendedStackTraceRendererFactory.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/pattern/ThrowableInvertedPropertyRendererFactory.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/pattern/ThrowableInvertedStackTraceRenderer.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/pattern/ThrowableInvertedStackTraceRendererFactory.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/pattern/ThrowablePatternConverter.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/pattern/ThrowablePropertyRenderer.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/pattern/ThrowablePropertyRendererFactory.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/pattern/ThrowableStackTraceRenderer.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/pattern/ThrowableStackTraceRendererFactory.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/util/Throwables.java
  log4j-layout-template-json/src/main/java/org/apache/logging/log4j/layout/template/json/resolver/StackTraceStringResolver.java
  src/site/antora/modules/ROOT/pages/manual/pattern-layout.adoc
Labels: layouts

#3050 Fix key removal issues in Thread Context
  log4j-api-test/src/test/java/org/apache/logging/log4j/CloseableThreadContextTest.java
  log4j-api-test/src/test/java/org/apache/logging/log4j/internal/map/UnmodifiableArrayBackedMapTest.java
  log4j-api/src/main/java/org/apache/logging/log4j/internal/map/UnmodifiableArrayBackedMap.java
  src/changelog/.2.x.x/3048_fix_ThreadContext_remove.xml
Labels: api

#3071 Fix Android-related issues in Log4j Core
  log4j-core/src/main/java/org/apache/logging/log4j/core/config/xml/XmlConfiguration.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/impl/Log4jContextFactory.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/lookup/JmxRuntimeInputArgumentsLookup.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/util/internal/SystemUtils.java
  src/changelog/.2.x.x/3056_android_support.xml
  src/site/antora/modules/ROOT/pages/faq.adoc
  src/site/antora/modules/ROOT/partials/manual/systemproperties/properties-context-selector.adoc
Labels: android

#3070 Remove JANSI dependency in `2.x`
  log4j-1.2-api/src/test/java/org/apache/log4j/config/AbstractLog4j1ConfigurationTest.java
  log4j-core-test/pom.xml
  log4j-core-test/src/main/java/org/apache/logging/log4j/core/test/categories/Layouts.java
  log4j-core-test/src/main/java/org/apache/logging/log4j/core/test/categories/package-info.java
  log4j-core-test/src/test/java/org/apache/logging/log4j/core/appender/ConsoleAppenderAnsiMessagesMain.java
  log4j-core-test/src/test/java/org/apache/logging/log4j/core/appender/ConsoleAppenderAnsiStyleJira180Main.java
  log4j-core-test/src/test/java/org/apache/logging/log4j/core/appender/ConsoleAppenderAnsiStyleJira272Main.java
  log4j-core-test/src/test/java/org/apache/logging/log4j/core/appender/ConsoleAppenderAnsiStyleJira319Main.java
  log4j-core-test/src/test/java/org/apache/logging/log4j/core/appender/ConsoleAppenderAnsiStyleLayoutMain.java
  log4j-core-test/src/test/java/org/apache/logging/log4j/core/appender/ConsoleAppenderAnsiStyleNameLayoutMain.java
  log4j-core-test/src/test/java/org/apache/logging/log4j/core/appender/ConsoleAppenderAnsiXExceptionMain.java
  log4j-core-test/src/test/java/org/apache/logging/log4j/core/appender/ConsoleAppenderDefaultSuppressedThrowable.java
  log4j-core-test/src/test/java/org/apache/logging/log4j/core/appender/ConsoleAppenderHighlightLayoutDefaultMain.java
  log4j-core-test/src/test/java/org/apache/logging/log4j/core/appender/ConsoleAppenderHighlightLayoutMain.java
  log4j-core-test/src/test/java/org/apache/logging/log4j/core/appender/ConsoleAppenderJAnsiMessageMain.java
  log4j-core-test/src/test/java/org/apache/logging/log4j/core/appender/ConsoleAppenderJira1002ShortThrowableLayoutMain.java
  log4j-core-test/src/test/java/org/apache/logging/log4j/core/appender/ConsoleAppenderNoAnsiStyleLayoutMain.java
  log4j-core-test/src/test/java/org/apache/logging/log4j/core/appender/JansiConsoleAppenderJira965.java
  log4j-core-test/src/test/java/org/apache/logging/log4j/core/impl/ThrowableFormatOptionsTest.java
  log4j-core-test/src/test/java/org/apache/logging/log4j/core/pattern/JAnsiTextRendererTest.java
  log4j-core-test/src/test/java/org/apache/logging/log4j/core/pattern/MessageAnsiConverterTest.java
  log4j-core-test/src/test/java/org/apache/logging/log4j/core/pattern/MessageStyledConverterTest.java
  log4j-core-test/src/test/resources/log4j2-console-msg-ansi.xml
  log4j-core/pom.xml
  log4j-core/src/main/java/org/apache/logging/log4j/core/appender/ConsoleAppender.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/impl/ThrowableFormatOptions.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/impl/package-info.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/layout/PatternLayout.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/pattern/AnsiEscape.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/pattern/JAnsiTextRenderer.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/pattern/MessagePatternConverter.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/pattern/package-info.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/util/Loader.java
  log4j-jakarta-smtp/src/test/java/org/apache/logging/log4j/smtp/SmtpAppenderAsyncTest.java
  log4j-parent/pom.xml
  pom.xml
  src/changelog/.2.x.x/.release-notes.adoc.ftl
  src/changelog/.2.x.x/1736_split_jansi_support.xml
  src/changelog/.2.x.x/2916_rewrite_jansi_renderer.xml
  src/site/antora/antora.tmpl.yml
  src/site/antora/antora.yml
  src/site/antora/modules/ROOT/pages/manual/appenders.adoc
  src/site/antora/modules/ROOT/pages/manual/pattern-layout.adoc
  src/site/antora/modules/ROOT/pages/manual/systemproperties.adoc
  src/site/antora/modules/ROOT/partials/manual/systemproperties/properties-jansi.adoc
Labels: dependencies, layouts

#3118 Create `DefaultLayout` independent of `PatternLayout`
  log4j-core/src/main/java/org/apache/logging/log4j/core/config/AbstractConfiguration.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/config/DefaultLayout.java
  src/changelog/.2.x.x/3118_default_layout.xml
Labels: layouts
