Repository apache/logging-log4j2, pull requests merged in 2024-01, with the labels that each got.

#2138 Fix use of AccessController in LoaderUtil
  log4j-api-test/src/test/java/org/apache/logging/log4j/util/LoaderUtilSecurityManagerTest.java
  log4j-api/src/main/java/org/apache/logging/log4j/util/LoaderUtil.java
  src/changelog/.2.x.x/fix_security_manager_use_in_LoaderUtil.xml
  src/site/_release-notes/_2.x.x.adoc
Labels: bug, runtime

#2168 Fix dead link to release notes and support on index.adoc
  src/site/asciidoc/index.adoc
Labels: documentation

#2209 Remove ineffective tests
  log4j-1.2-api/src/test/java/org/apache/log4j/defaultInit/TestCase1.java
  log4j-1.2-api/src/test/java/org/apache/log4j/defaultInit/TestCase2.java
  log4j-1.2-api/src/test/java/org/apache/log4j/defaultInit/TestCase3.java
  log4j-1.2-api/src/test/java/org/apache/log4j/defaultInit/TestCase4.java
  log4j-1.2-api/src/test/java/org/apache/log4j/helpers/OptionConverterTestCase.java
  log4j-1.2-api/src/test/java/org/apache/log4j/helpers/PatternParserTestCase.java
  log4j-1.2-api/src/test/java/org/apache/log4j/xml/DOMTestCase.java
  log4j-config-yaml/src/test/java/org/apache/logging/log4j/config/yaml/MultipleTriggeringPolicyTest.java
  log4j-core-its/pom.xml
  log4j-core-its/src/test/java/org/apache/logging/log4j/FilterPerformanceComparison.java
  log4j-core-its/src/test/java/org/apache/logging/log4j/PerformanceComparison.java
  log4j-core-its/src/test/java/org/apache/logging/log4j/PerformanceRun.java
  log4j-core-its/src/test/java/org/apache/logging/log4j/core/SimplePerfTest.java
  log4j-core-its/src/test/java/org/apache/logging/log4j/core/ThreadedPerfTest.java
  log4j-core-its/src/test/java/org/apache/logging/log4j/core/ThreadedTest.java
  log4j-core-its/src/test/java/org/apache/logging/log4j/core/appender/HttpAppenderTest.java
  log4j-core-its/src/test/java/org/apache/logging/log4j/core/appender/SecureSocketAppenderSocketOptionsTest.java
  log4j-core-its/src/test/java/org/apache/logging/log4j/core/appender/SocketAppenderBufferSizeTest.java
  log4j-core-its/src/test/java/org/apache/logging/log4j/core/appender/SocketAppenderSocketOptionsTest.java
  log4j-core-its/src/test/java/org/apache/logging/log4j/core/appender/SocketAppenderTest.java
  log4j-core-its/src/test/java/org/apache/logging/log4j/core/async/perftest/AbstractRunQueue.java
  log4j-core-its/src/test/java/org/apache/logging/log4j/core/async/perftest/Histogram.java
  log4j-core-its/src/test/java/org/apache/logging/log4j/core/async/perftest/IPerfTestRunner.java
  log4j-core-its/src/test/java/org/apache/logging/log4j/core/async/perftest/IdleStrategy.java
  log4j-core-its/src/test/java/org/apache/logging/log4j/core/async/perftest/MultiThreadPerfTest.java
  log4j-core-its/src/test/java/org/apache/logging/log4j/core/async/perftest/NoOpIdleStrategy.java
  log4j-core-its/src/test/java/org/apache/logging/log4j/core/async/perftest/PerfTest.java
  log4j-core-its/src/test/java/org/apache/logging/log4j/core/async/perftest/PerfTestDriver.java
  log4j-core-its/src/test/java/org/apache/logging/log4j/core/async/perftest/PerfTestResultFormatter.java
  log4j-core-its/src/test/java/org/apache/logging/log4j/core/async/perftest/ResponseTimeTest.java
  log4j-core-its/src/test/java/org/apache/logging/log4j/core/async/perftest/RunConversant.java
  log4j-core-its/src/test/java/org/apache/logging/log4j/core/async/perftest/RunJCTools.java
  log4j-core-its/src/test/java/org/apache/logging/log4j/core/async/perftest/RunLog4j1.java
  log4j-core-its/src/test/java/org/apache/logging/log4j/core/async/perftest/RunLog4j2.java
  log4j-core-its/src/test/java/org/apache/logging/log4j/core/async/perftest/RunLogback.java
  log4j-core-its/src/test/java/org/apache/logging/log4j/core/async/perftest/SimplePerfTest.java
  log4j-core-its/src/test/java/org/apache/logging/log4j/core/async/perftest/YieldIdleStrategy.java
  log4j-core-its/src/test/resources/logback-test.xml
  log4j-core-test/src/test/java/org/apache/logging/log4j/core/CollectionLoggingTest.java
  log4j-core-test/src/test/java/org/apache/logging/log4j/core/LogEventTest.java
  log4j-core-test/src/test/java/org/apache/logging/log4j/core/appender/FileAppenderTest.java
  log4j-core-test/src/test/java/org/apache/logging/log4j/core/appender/RollingRandomAccessFileAppenderRolloverTest.java
  log4j-core-test/src/test/java/org/apache/logging/log4j/core/appender/rolling/RollingAppenderCronOnceADayTest.java
  log4j-core-test/src/test/java/org/apache/logging/log4j/core/appender/rolling/RollingDirectSizeTimeNewDirectoryTest.java
  log4j-core-test/src/test/java/org/apache/logging/log4j/core/appender/rolling/RollingRandomAccessFileManagerHeaderFooterTest.java
  log4j-core-test/src/test/java/org/apache/logging/log4j/core/async/AsyncLoggerTest.java
  log4j-core-test/src/test/java/org/apache/logging/log4j/core/async/AsyncWaitStrategyFactoryConfigGlobalLoggersTest.java
  log4j-core-test/src/test/java/org/apache/logging/log4j/core/async/QueueFullAsyncLoggerLoggingFromToStringTest2.java
  log4j-core-test/src/test/java/org/apache/logging/log4j/core/config/xml/XmlSchemaTest.java
  log4j-core-test/src/test/java/org/apache/logging/log4j/core/net/ssl/StoreConfigurationTest.java
  log4j-core-test/src/test/java/org/apache/logging/log4j/core/util/InitTest.java
  log4j-core-test/src/test/resources/AsyncWaitStrategyFactoryConfigGlobalLoggerTest.xml
  log4j-core-test/src/test/resources/HttpAppenderTest.xml
  log4j-core-test/src/test/resources/RollingRandomAccessFileAppenderHeaderFooterTest.xml
  log4j-core-test/src/test/resources/log4j-collectionLogging.xml
  log4j-layout-template-json-test/src/test/java/org/apache/logging/log4j/layout/template/json/EcsLayoutTest.java
  log4j-layout-template-json-test/src/test/java/org/apache/logging/log4j/layout/template/json/LogstashIT.java
  log4j-perf-test/src/main/java/org/apache/logging/log4j/perf/jmh/AsyncLoggersBenchmark.java
  pom.xml
Labels: tests

#2239 Fix forgotten `threadName` field in `RingBufferLogEvent#clear()` (#2234)
  log4j-core-test/src/test/java/org/apache/logging/log4j/core/async/RingBufferLogEventTest.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/async/RingBufferLogEvent.java
  src/changelog/.2.x.x/fix_RingBufferLogEvent_clear.xml
Labels: bug, async

#2219 Add security threat model to docs
  src/site/asciidoc/download.adoc.vm
  src/site/asciidoc/manual/layouts.adoc
  src/site/asciidoc/security.adoc
Labels: documentation
