Repository apache/logging-log4j2, pull requests merged in 2024-04, with the labels that each got.

#2498 Add trace context fields to GcpLayout.json
  log4j-layout-template-json-test/src/test/java/org/apache/logging/log4j/layout/template/json/GcpLayoutTest.java
  log4j-layout-template-json/src/main/resources/GcpLayout.json
  src/changelog/.2.x.x/add_GcpLayout_tracing_support.xml
Labels: enhancement, layouts

#2505 Fix handling of `log4j2.messageFactory` and `log4j2.flowMessageFactory` properties
  log4j-api/src/main/java/org/apache/logging/log4j/spi/AbstractLogger.java
  log4j-core-test/src/test/java/org/apache/logging/log4j/core/LoggerMessageFactoryCustomizationTest.java
  log4j-core-test/src/test/java/org/apache/logging/log4j/core/LoggerMessageFactoryDefaultsTlaDisabledTest.java
  log4j-core-test/src/test/java/org/apache/logging/log4j/core/LoggerMessageFactoryDefaultsTlaEnabledTest.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/Logger.java
  src/changelog/.2.x.x/2379_fix_message_factory_properties.xml
Labels: bug, api

#2549 Revamp the F.A.Q. page
  src/site/antora/modules/ROOT/images/whichjar-2.x.png
  src/site/antora/modules/ROOT/images/whichjar-log4j-1.2-api.png
  src/site/antora/modules/ROOT/images/whichjar-log4j-api.png
  src/site/antora/modules/ROOT/images/whichjar-slf4j-2.x.png
  src/site/antora/modules/ROOT/pages/faq.adoc
Labels: documentation

#2551 Add a new `Development` page
  BUILDING.adoc
  src/site/antora/modules/ROOT/nav.adoc
  src/site/antora/modules/ROOT/pages/development.adoc
  src/site/antora/modules/ROOT/pages/guidelines.adoc
Labels: documentation
