Repository apache/logging-log4j2, pull requests merged in 2024-11, with the labels that each got.

#3175 Document API compatibility checks
  BUILDING.adoc
Labels: documentation

#3150 Port date & time formatter rewrite to `main`
  log4j-core-test/src/test/java/org/apache/logging/log4j/core/appender/FileAppenderTest.java
  log4j-core-test/src/test/java/org/apache/logging/log4j/core/appender/rolling/OnStartupTriggeringPolicyTest.java
  log4j-core-test/src/test/java/org/apache/logging/log4j/core/appender/rolling/RollingAppenderDeleteAccumulatedCount1Test.java
  log4j-core-test/src/test/java/org/apache/logging/log4j/core/appender/rolling/RollingAppenderDeleteAccumulatedCount2Test.java
  log4j-core-test/src/test/java/org/apache/logging/log4j/core/appender/rolling/RollingAppenderDeleteAccumulatedSizeTest.java
  log4j-core-test/src/test/java/org/apache/logging/log4j/core/appender/rolling/RollingAppenderDeleteNestedTest.java
  log4j-core-test/src/test/java/org/apache/logging/log4j/core/config/plugins/LegacyPluginTest.java
  log4j-core-test/src/test/java/org/apache/logging/log4j/core/layout/HtmlLayoutTest.java
  log4j-core-test/src/test/java/org/apache/logging/log4j/core/pattern/DatePatternConverterTest.java
  log4j-core-test/src/test/java/org/apache/logging/log4j/core/pattern/PatternParserTest.java
  log4j-core-test/src/test/java/org/apache/logging/log4j/core/time/InstantFormatterTest.java
  log4j-core-test/src/test/java/org/apache/logging/log4j/core/time/internal/format/FixedDateFormatTest.java
  log4j-core-test/src/test/java/org/apache/logging/log4j/core/util/internal/instant/InstantNumberFormatterTest.java
  log4j-core-test/src/test/java/org/apache/logging/log4j/core/util/internal/instant/InstantPatternDynamicFormatterTest.java
  log4j-core-test/src/test/java/org/apache/logging/log4j/core/util/internal/instant/InstantPatternThreadLocalCachedFormatterTest.java
  log4j-core-test/src/test/resources/legacy-plugins.xml
  log4j-core-test/src/test/resources/log4j-rolling-size-with-time.xml
  log4j-core/src/main/java/org/apache/logging/log4j/core/layout/HtmlLayout.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/pattern/DatePatternConverter.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/pattern/FileDatePatternConverter.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/time/InstantFormatter.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/time/internal/format/DatePrinter.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/time/internal/format/FastDateFormat.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/time/internal/format/FastDatePrinter.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/time/internal/format/FixedDateFormat.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/time/internal/format/Format.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/time/internal/format/FormatCache.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/util/datetime/DatePrinter.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/util/datetime/FastDateFormat.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/util/datetime/package-info.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/util/internal/instant/InstantFormatter.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/util/internal/instant/InstantNumberFormatter.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/util/internal/instant/InstantPatternDynamicFormatter.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/util/internal/instant/InstantPatternFormatter.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/util/internal/instant/InstantPatternThreadLocalCachedFormatter.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/util/internal/instant/package-info.java
  log4j-layout-template-json-test/src/main/java/org/apache/logging/log4j/layout/template/json/LogEventFixture.java
  log4j-layout-template-json-test/src/main/java/org/apache/logging/log4j/layout/template/json/package-info.java
  log4j-layout-template-json/src/main/java/org/apache/logging/log4j/layout/template/json/resolver/TimestampResolver.java
  log4j-perf-test/src/main/java/org/apache/logging/log4j/perf/jmh/DateTimeFormatBenchmark.java
  log4j-perf-test/src/main/java/org/apache/logging/log4j/perf/jmh/ThreadsafeDateFormatBenchmark.java
  log4j-perf-test/src/main/java/org/apache/logging/log4j/perf/jmh/TimeFormatBenchmark.java
  log4j-perf-test/src/main/java/org/apache/logging/log4j/perf/jmh/instant/InstantPatternDynamicFormatterSequencingBenchmark.java
  log4j-perf-test/src/main/java/org/apache/logging/log4j/perf/jmh/instant/InstantPatternFormatterBenchmark.java
  log4j-perf-test/src/main/java/org/apache/logging/log4j/perf/jmh/instant/InstantPatternFormatterImpactBenchmark.java
  src/changelog/.3.x.x/3149_remove_named_date_patterns.xml
  src/changelog/.index.adoc.ftl
  src/site/antora/modules/ROOT/pages/manual/pattern-layout.adoc
Labels: performance, layouts

#3154 Port `%xEx` performance regression fix to `main`
  log4j-core-test/src/test/java/org/apache/logging/log4j/core/appender/rewrite/MapRewritePolicyTest.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/pattern/ClassResourceInfo.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/pattern/PatternParser.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/pattern/ThrowableExtendedStackTraceRenderer.java
  log4j-csv/src/main/java/org/apache/logging/log4j/csv/layout/CsvLogEventLayout.java
  src/site/antora/modules/ROOT/pages/manual/pattern-layout.adoc
Labels: performance, layouts

#3186 Fix code typo in the thread context docs
  src/site/antora/modules/ROOT/pages/manual/thread-context.adoc
Labels: documentation

#3067 refactor(1.2-api): migrate to junit5
  log4j-1.2-api/pom.xml
  log4j-1.2-api/src/test/java/org/apache/log4j/CallerInformationTest.java
  log4j-1.2-api/src/test/java/org/apache/log4j/CategoryTest.java
  log4j-1.2-api/src/test/java/org/apache/log4j/LevelTest.java
  log4j-1.2-api/src/test/java/org/apache/log4j/LogManagerTest.java
  log4j-1.2-api/src/test/java/org/apache/log4j/LogWithMDCTest.java
  log4j-1.2-api/src/test/java/org/apache/log4j/LogWithRouteTest.java
  log4j-1.2-api/src/test/java/org/apache/log4j/LoggerJira3410Test.java
  log4j-1.2-api/src/test/java/org/apache/log4j/LoggerTest.java
  log4j-1.2-api/src/test/java/org/apache/log4j/LoggingTest.java
  log4j-1.2-api/src/test/java/org/apache/log4j/MDCTestCase.java
  log4j-1.2-api/src/test/java/org/apache/log4j/NDCTest.java
  log4j-1.2-api/src/test/java/org/apache/log4j/PriorityTest.java
  log4j-1.2-api/src/test/java/org/apache/log4j/PropertyConfiguratorTest.java
  log4j-1.2-api/src/test/java/org/apache/log4j/bridge/LogEventWrapperTest.java
  log4j-1.2-api/src/test/java/org/apache/log4j/config/AbstractLog4j1ConfigurationConverterTest.java
  log4j-1.2-api/src/test/java/org/apache/log4j/config/AbstractLog4j1ConfigurationTest.java
  log4j-1.2-api/src/test/java/org/apache/log4j/config/AutoConfigTest.java
  log4j-1.2-api/src/test/java/org/apache/log4j/config/Log4j1ConfigurationConverterHadoopTest.java
  log4j-1.2-api/src/test/java/org/apache/log4j/config/Log4j1ConfigurationConverterSparkTest.java
  log4j-1.2-api/src/test/java/org/apache/log4j/config/Log4j1ConfigurationFactoryTest.java
  log4j-1.2-api/src/test/java/org/apache/log4j/config/MapRewriteAppenderTest.java
  log4j-1.2-api/src/test/java/org/apache/log4j/config/PropertiesConfigurationFactoryTest.java
  log4j-1.2-api/src/test/java/org/apache/log4j/config/PropertiesConfigurationTest.java
  log4j-1.2-api/src/test/java/org/apache/log4j/config/PropertiesReconfigurationTest.java
  log4j-1.2-api/src/test/java/org/apache/log4j/config/PropertiesRollingWithPropertiesTest.java
  log4j-1.2-api/src/test/java/org/apache/log4j/config/RewriteAppenderTest.java
  log4j-1.2-api/src/test/java/org/apache/log4j/config/SocketAppenderConfigurationTest.java
  log4j-1.2-api/src/test/java/org/apache/log4j/config/SyslogAppenderConfigurationTest.java
  log4j-1.2-api/src/test/java/org/apache/log4j/config/SyslogAppenderTest.java
  log4j-1.2-api/src/test/java/org/apache/log4j/config/TestConfigurator.java
  log4j-1.2-api/src/test/java/org/apache/log4j/config/XmlConfigurationFactoryTest.java
  log4j-1.2-api/src/test/java/org/apache/log4j/config/XmlConfigurationTest.java
  log4j-1.2-api/src/test/java/org/apache/log4j/config/XmlReconfigurationTest.java
  log4j-1.2-api/src/test/java/org/apache/log4j/config/XmlRollingWithPropertiesTest.java
  log4j-1.2-api/src/test/java/org/apache/log4j/helpers/CyclicBufferTestCase.java
  log4j-1.2-api/src/test/java/org/apache/log4j/helpers/UtilLoggingLevelTest.java
  log4j-1.2-api/src/test/java/org/apache/log4j/layout/Log4j1XmlLayoutTest.java
  log4j-1.2-api/src/test/java/org/apache/log4j/pattern/Log4j1MdcPatternConverterTest.java
  log4j-1.2-api/src/test/java/org/apache/log4j/pattern/Log4j1NdcPatternConverterTest.java
  log4j-1.2-api/src/test/java/org/apache/log4j/util/SerializationTestHelper.java
Labels: tests

#3212 Fix off-by-one in `StackTraceStringResolver`
  log4j-layout-template-json-test/src/test/java/org/apache/logging/log4j/layout/template/json/resolver/StackTraceStringResolverTest.java
  log4j-layout-template-json/src/main/java/org/apache/logging/log4j/layout/template/json/resolver/StackTraceStringResolver.java
  src/changelog/.2.x.x/3212_fix_JTL_StackTraceStringResolver.xml
Labels: bug, layouts

#3216 Fix off-by-one in `StackTraceStringResolver`
  log4j-layout-template-json-test/src/test/java/org/apache/logging/log4j/layout/template/json/resolver/StackTraceStringResolverTest.java
  log4j-layout-template-json/src/main/java/org/apache/logging/log4j/layout/template/json/resolver/StackTraceStringResolver.java
  src/changelog/.2.x.x/3216_fix_JTL_StackTraceStringResolver.xml
Labels: bug, layouts
