Repository apache/logging-log4j2, pull requests merged in 2024-08, with the labels that each got.

#2772 Revamp file and delegating appenders
  pom.xml
  src/site/antora/antora.tmpl.yml
  src/site/antora/antora.yml
  src/site/antora/modules/ROOT/examples/manual/appenders/delegating/async.json
  src/site/antora/modules/ROOT/examples/manual/appenders/delegating/async.properties
  src/site/antora/modules/ROOT/examples/manual/appenders/delegating/async.xml
  src/site/antora/modules/ROOT/examples/manual/appenders/delegating/async.yaml
  src/site/antora/modules/ROOT/examples/manual/appenders/delegating/failover.json
  src/site/antora/modules/ROOT/examples/manual/appenders/delegating/failover.properties
  src/site/antora/modules/ROOT/examples/manual/appenders/delegating/failover.xml
  src/site/antora/modules/ROOT/examples/manual/appenders/delegating/failover.yaml
  src/site/antora/modules/ROOT/examples/manual/appenders/delegating/rewrite.json
  src/site/antora/modules/ROOT/examples/manual/appenders/delegating/rewrite.properties
  src/site/antora/modules/ROOT/examples/manual/appenders/delegating/rewrite.xml
  src/site/antora/modules/ROOT/examples/manual/appenders/delegating/rewrite.yaml
  src/site/antora/modules/ROOT/examples/manual/appenders/delegating/routing-definition.json
  src/site/antora/modules/ROOT/examples/manual/appenders/delegating/routing-definition.properties
  src/site/antora/modules/ROOT/examples/manual/appenders/delegating/routing-definition.xml
  src/site/antora/modules/ROOT/examples/manual/appenders/delegating/routing-definition.yaml
  src/site/antora/modules/ROOT/examples/manual/appenders/delegating/routing-ref.json
  src/site/antora/modules/ROOT/examples/manual/appenders/delegating/routing-ref.properties
  src/site/antora/modules/ROOT/examples/manual/appenders/delegating/routing-ref.xml
  src/site/antora/modules/ROOT/examples/manual/appenders/delegating/routing-ref.yaml
  src/site/antora/modules/ROOT/examples/manual/appenders/delegating/routing-script.json
  src/site/antora/modules/ROOT/examples/manual/appenders/delegating/routing-script.properties
  src/site/antora/modules/ROOT/examples/manual/appenders/delegating/routing-script.xml
  src/site/antora/modules/ROOT/examples/manual/appenders/delegating/routing-script.yaml
  src/site/antora/modules/ROOT/examples/manual/appenders/rolling-file/logrotate.json
  src/site/antora/modules/ROOT/examples/manual/appenders/rolling-file/logrotate.properties
  src/site/antora/modules/ROOT/examples/manual/appenders/rolling-file/logrotate.xml
  src/site/antora/modules/ROOT/examples/manual/appenders/rolling-file/logrotate.yaml
  src/site/antora/modules/ROOT/examples/manual/appenders/rolling-file/per-month.json
  src/site/antora/modules/ROOT/examples/manual/appenders/rolling-file/per-month.properties
  src/site/antora/modules/ROOT/examples/manual/appenders/rolling-file/per-month.xml
  src/site/antora/modules/ROOT/examples/manual/appenders/rolling-file/per-month.yaml
  src/site/antora/modules/ROOT/examples/manual/appenders/rolling-file/policies.json
  src/site/antora/modules/ROOT/examples/manual/appenders/rolling-file/policies.properties
  src/site/antora/modules/ROOT/examples/manual/appenders/rolling-file/policies.xml
  src/site/antora/modules/ROOT/examples/manual/appenders/rolling-file/policies.yaml
  src/site/antora/modules/ROOT/examples/manual/appenders/rolling-file/script-condition.groovy
  src/site/antora/modules/ROOT/examples/manual/appenders/rolling-file/script-condition.json
  src/site/antora/modules/ROOT/examples/manual/appenders/rolling-file/script-condition.properties
  src/site/antora/modules/ROOT/examples/manual/appenders/rolling-file/script-condition.xml
  src/site/antora/modules/ROOT/examples/manual/appenders/rolling-file/script-condition.yaml
  src/site/antora/modules/ROOT/examples/manual/appenders/rolling-file/timestamped.json
  src/site/antora/modules/ROOT/examples/manual/appenders/rolling-file/timestamped.properties
  src/site/antora/modules/ROOT/examples/manual/appenders/rolling-file/timestamped.xml
  src/site/antora/modules/ROOT/examples/manual/appenders/rolling-file/timestamped.yaml
  src/site/antora/modules/ROOT/nav.adoc
  src/site/antora/modules/ROOT/pages/manual/appenders.adoc
  src/site/antora/modules/ROOT/pages/manual/appenders/delegating.adoc
  src/site/antora/modules/ROOT/pages/manual/appenders/file.adoc
  src/site/antora/modules/ROOT/pages/manual/appenders/rolling-file.adoc
Labels: documentation

#2790 Revamp database appenders
  log4j-jpa/pom.xml
  src/site/antora/modules/ROOT/examples/manual/appenders/database/LogEventEntity.java
  src/site/antora/modules/ROOT/examples/manual/appenders/database/cassandra.json
  src/site/antora/modules/ROOT/examples/manual/appenders/database/cassandra.properties
  src/site/antora/modules/ROOT/examples/manual/appenders/database/cassandra.sql
  src/site/antora/modules/ROOT/examples/manual/appenders/database/cassandra.xml
  src/site/antora/modules/ROOT/examples/manual/appenders/database/cassandra.yaml
  src/site/antora/modules/ROOT/examples/manual/appenders/database/column-mapping.json
  src/site/antora/modules/ROOT/examples/manual/appenders/database/column-mapping.properties
  src/site/antora/modules/ROOT/examples/manual/appenders/database/column-mapping.xml
  src/site/antora/modules/ROOT/examples/manual/appenders/database/column-mapping.yaml
  src/site/antora/modules/ROOT/examples/manual/appenders/database/jdbc.json
  src/site/antora/modules/ROOT/examples/manual/appenders/database/jdbc.properties
  src/site/antora/modules/ROOT/examples/manual/appenders/database/jdbc.sql
  src/site/antora/modules/ROOT/examples/manual/appenders/database/jdbc.xml
  src/site/antora/modules/ROOT/examples/manual/appenders/database/jdbc.yaml
  src/site/antora/modules/ROOT/examples/manual/appenders/database/jpa.json
  src/site/antora/modules/ROOT/examples/manual/appenders/database/jpa.properties
  src/site/antora/modules/ROOT/examples/manual/appenders/database/jpa.xml
  src/site/antora/modules/ROOT/examples/manual/appenders/database/jpa.yaml
  src/site/antora/modules/ROOT/examples/manual/appenders/database/nosql-couch.json
  src/site/antora/modules/ROOT/examples/manual/appenders/database/nosql-couch.properties
  src/site/antora/modules/ROOT/examples/manual/appenders/database/nosql-couch.xml
  src/site/antora/modules/ROOT/examples/manual/appenders/database/nosql-couch.yaml
  src/site/antora/modules/ROOT/examples/manual/appenders/database/nosql-log-event.json
  src/site/antora/modules/ROOT/examples/manual/appenders/database/nosql-mongo-keys.json
  src/site/antora/modules/ROOT/examples/manual/appenders/database/nosql-mongo-keys.properties
  src/site/antora/modules/ROOT/examples/manual/appenders/database/nosql-mongo-keys.xml
  src/site/antora/modules/ROOT/examples/manual/appenders/database/nosql-mongo-keys.yaml
  src/site/antora/modules/ROOT/examples/manual/appenders/database/nosql-mongo.json
  src/site/antora/modules/ROOT/examples/manual/appenders/database/nosql-mongo.properties
  src/site/antora/modules/ROOT/examples/manual/appenders/database/nosql-mongo.xml
  src/site/antora/modules/ROOT/examples/manual/appenders/database/nosql-mongo.yaml
  src/site/antora/modules/ROOT/examples/manual/appenders/database/persistence.xml
  src/site/antora/modules/ROOT/nav.adoc
  src/site/antora/modules/ROOT/pages/javadoc.adoc
  src/site/antora/modules/ROOT/pages/manual/appenders.adoc
  src/site/antora/modules/ROOT/pages/manual/appenders/database.adoc
  src/site/antora/modules/ROOT/pages/manual/appenders/rolling-file.adoc
  src/site/antora/modules/ROOT/pages/manual/layouts.adoc
  src/site/antora/modules/ROOT/pages/manual/thread-context.adoc
Labels: documentation, appenders

#2795 Implement `LocationAware` for `FileLocationPatternConverter` (#2781)
  log4j-core-test/src/test/java/org/apache/logging/log4j/core/pattern/LocationPatternConvertersRequireLocationTest.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/pattern/FileLocationPatternConverter.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/pattern/package-info.java
  src/changelog/.2.x.x/2781_fix_file_location_pattern_converter_location_requirement.xml
Labels: layouts, async

#2782 Add missing `FileLocationPatternConverter#requiresLocation()` (#2781)
  log4j-core-test/src/test/java/org/apache/logging/log4j/core/pattern/LocationPatternConvertersRequireLocationTest.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/pattern/FileLocationPatternConverter.java
Labels: layouts, async

#2783 Disable programmatic configuration if `log4j1.compatibility` is `false`
  log4j-1.2-api/src/main/java/org/apache/log4j/PropertyConfigurator.java
  log4j-1.2-api/src/main/java/org/apache/log4j/xml/DOMConfigurator.java
  log4j-1.2-api/src/test/java/org/apache/log4j/PropertyConfiguratorTest.java
  log4j-1.2-api/src/test/java/org/apache/log4j/xml/DOMTestCase.java
  log4j-1.2-api/src/test/resources/DOMTestCase/DOMTest4.xml
  log4j-1.2-api/src/test/resources/DOMTestCase/DOMTest4_A1.xml
  log4j-1.2-api/src/test/resources/DOMTestCase/DOMTest4_A2.xml
  log4j-1.2-api/src/test/resources/DOMTestCase/DOMTestCase1.xml
  log4j-1.2-api/src/test/resources/DOMTestCase/categoryfactory1.xml
  log4j-1.2-api/src/test/resources/DOMTestCase/categoryfactory2.xml
  log4j-1.2-api/src/test/resources/DOMTestCase/defaultInit.xml
  log4j-1.2-api/src/test/resources/DOMTestCase/loggerfactory1.xml
  log4j-1.2-api/src/test/resources/DOMTestCase/testReset.xml
  log4j-1.2-api/src/test/resources/DOMTestCase/throwableRenderer1.xml
  log4j-1.2-api/src/test/resources/PropertyConfiguratorTest/badEscape.properties
  log4j-1.2-api/src/test/resources/PropertyConfiguratorTest/filter.properties
  log4j-1.2-api/src/test/resources/log4j1-1.2.17/input/xml/DOMTest4.xml
  log4j-1.2-api/src/test/resources/log4j1-1.2.17/input/xml/SocketAppenderTestConfig.xml
  log4j-1.2-api/src/test/resources/log4j1-1.2.17/input/xml/customLevel2.xml
  log4j-1.2-api/src/test/resources/log4j1-1.2.17/input/xml/customLevel3.xml
  log4j-1.2-api/src/test/resources/log4j1-1.2.17/input/xml/customLevel4.xml
  log4j-1.2-api/src/test/resources/log4j1-1.2.17/input/xml/customLogger1.xml
  log4j-1.2-api/src/test/resources/log4j1-1.2.17/input/xml/customLogger2.xml
  log4j-1.2-api/src/test/resources/log4j1-1.2.17/input/xml/customLogger3.xml
  log4j-1.2-api/src/test/resources/log4j1-1.2.17/input/xml/fallback1.xml
  log4j-1.2-api/src/test/resources/log4j1-1.2.17/input/xml/smtpAppender1.xml
  src/changelog/.2.x.x/2778_configurator_no_op.xml
Labels: bug, legacy-1.2-bridge

#2815 Fix `JsonLayout` failures under JPMS
  log4j-core/src/main/java/org/apache/logging/log4j/core/jackson/ContextDataAsEntryListDeserializer.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/jackson/ContextDataAsEntryListSerializer.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/jackson/ContextDataDeserializer.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/jackson/ContextDataSerializer.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/jackson/Initializers.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/jackson/JsonConstants.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/jackson/Log4jJsonModule.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/jackson/Log4jXmlModule.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/jackson/Log4jYamlModule.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/jackson/LogEventMixIn.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/jackson/LogEventWithContextListMixIn.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/jackson/MapEntry.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/jackson/package-info.java
  src/changelog/.2.x.x/2814_open_json_layout.xml
Labels: bug, layouts, jpms

#2854 Disable level modification via JUL by default
  log4j-jul/src/main/java/org/apache/logging/log4j/jul/LogManager.java
  log4j-jul/src/test/java/org/apache/logging/log4j/jul/test/ApiLoggerTest.java
  log4j-jul/src/test/java/org/apache/logging/log4j/jul/test/CoreLoggerTest.java
  src/changelog/.2.x.x/2353_set_level_no-op.xml
  src/site/antora/modules/ROOT/partials/manual/systemproperties/properties-log4j-jul.adoc
Labels: api, JUL

#2849 Remove properties cache and token-based matching
  log4j-api-test/src/test/java/org/apache/logging/log4j/util/PropertiesUtilOrderTest.java
  log4j-api-test/src/test/java/org/apache/logging/log4j/util/PropertiesUtilTest.java
  log4j-api-test/src/test/resources/Jira3413Test.properties
  log4j-api/src/main/java/org/apache/logging/log4j/util/PropertiesUtil.java
  log4j-core-test/src/test/java/org/apache/logging/log4j/core/async/AsyncQueueFullPolicyFactoryTest.java
  log4j-core-test/src/test/java/org/apache/logging/log4j/core/impl/ThreadContextDataInjectorTest.java
  log4j-core-test/src/test/java/org/apache/logging/log4j/core/net/ssl/SslConfigurationFactoryTest.java
  log4j-jpa/src/test/java/org/apache/logging/log4j/core/appender/db/jpa/AbstractJpaAppenderTest.java
  src/changelog/.2.x.x/2849-remove-token-based-matching.xml
Labels: enhancement, api

#2853 Add `useFqdn` attribute to RFC5424 Layout
  log4j-core-test/src/test/java/org/apache/logging/log4j/core/layout/Rfc5424LayoutTest.java
  log4j-core-test/src/test/java/org/apache/logging/log4j/core/util/NetUtilsTest.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/appender/SyslogAppender.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/layout/Rfc5424Layout.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/layout/package-info.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/util/NetUtils.java
  src/changelog/.2.x.x/1740_rfc5424_use_fqdn.xml
Labels: bug, runtime, layouts
