Repository apache/logging-log4j2, pull requests merged in 2025-06, with the labels that each got.

#3703 Add option to provide URIs to monitor in addition to the config file
  log4j-core-test/src/test/java/org/apache/logging/log4j/core/MonitorResourcesTest.java
  log4j-core-test/src/test/java/org/apache/logging/log4j/core/async/AsyncWaitStrategyFactoryConfigTest.java
  log4j-core-test/src/test/resources/AsyncWaitStrategyFactoryConfigTest.properties
  log4j-core-test/src/test/resources/config/MonitorResource/log4j.json
  log4j-core-test/src/test/resources/config/MonitorResource/log4j.properties
  log4j-core-test/src/test/resources/config/MonitorResource/log4j.xml
  log4j-core-test/src/test/resources/config/MonitorResource/log4j.yaml
  log4j-core/src/main/java/org/apache/logging/log4j/core/config/AbstractConfiguration.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/config/MonitorResource.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/config/MonitorResources.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/config/builder/api/ConfigurationBuilder.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/config/builder/api/package-info.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/config/builder/impl/BuiltConfiguration.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/config/builder/impl/DefaultConfigurationBuilder.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/config/builder/impl/package-info.java
  log4j-core/src/main/java/org/apache/logging/log4j/core/config/properties/PropertiesConfigurationBuilder.java
  src/changelog/.2.x.x/3074_monitor_additional_files.xml
  src/site/antora/modules/ROOT/examples/manual/configuration/monitor-resources.json
  src/site/antora/modules/ROOT/examples/manual/configuration/monitor-resources.properties
  src/site/antora/modules/ROOT/examples/manual/configuration/monitor-resources.xml
  src/site/antora/modules/ROOT/examples/manual/configuration/monitor-resources.yaml
  src/site/antora/modules/ROOT/pages/manual/configuration.adoc
Labels: api, configuration

#3757 docs: Update Javadoc output path to match plugin changes
  pom.xml
Labels: bug, dependencies, build

#3762 Pin `spotbugs-annotations` version to `4.8.6`
  .github/dependabot.yaml
  log4j-parent/pom.xml
Labels: bug, dependencies

#3768 Fix UuidPatternConverter javadoc/adoc
  log4j-core/src/main/java/org/apache/logging/log4j/core/pattern/UuidPatternConverter.java
  src/site/antora/modules/ROOT/pages/manual/pattern-layout.adoc
Labels: documentation

#3778 fix: correctly detect Disruptor major version
  log4j-core/src/main/java/org/apache/logging/log4j/core/async/DisruptorUtil.java
  log4j-osgi-test/pom.xml
  log4j-osgi-test/src/test/java/org/apache/logging/log4j/osgi/tests/DisruptorTest.java
  src/changelog/.2.x.x/3706_disruptor-tccl.xml
Labels: bug, dependencies, async
